exclude: |
    (?x)^(
        build/.*|
        tmp/.*|
        helloworld|
        helloworld*.dSYM|
        .*\.o|
        .*\.x86_64|
        .*\.arm64|
    )$
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v1.1.1
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        exclude: .*\.patch
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.30.0
  hooks:
  - id: markdownlint
-   repo: https://github.com/detailyang/pre-commit-shell.git
    rev: 1.0.2
    hooks:
    -   id: shell-lint
        args: ["--exclude=SC1090,SC1091,SC2034,SC2039,SC2140,SC2148,SC2153,SC2154,SC2164"]
- repo: https://github.com/pocc/pre-commit-hooks
  rev: v1.3.5
  hooks:
    - id: clang-format
      args: [--style=Google]
    - id: oclint
      args: [-p=build]
    - id: uncrustify
    - id: cppcheck
    - id: cpplint
    - id: include-what-you-use
